# DisableSpawners Config
# For help with the configuration file, please see the plugin BukkitDev page

Disable Spawners On:
  - ExampleWorld
  - AnotherExampleWorld
  - RemoveTheseAndAddYourOwn
  - WorldsYouWantToDisableSpawnersOn